# Generated by Django 5.0.1 on 2024-01-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_city_city_name_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
