# Generated by Django 5.0.1 on 2024-01-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_user_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
    ]
