# Generated by Django 5.0.1 on 2024-01-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_user_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='logo',
            new_name='logos',
        ),
    ]
