# Generated by Django 5.0.1 on 2024-01-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_rename_logo_user_logos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='logos',
            new_name='logo',
        ),
    ]
