# Generated by Django 5.0.1 on 2024-01-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='adcode',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='city',
            name='city_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
