# Generated by Django 5.0.1 on 2024-01-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_city_adcode_city_city_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_code', models.CharField(max_length=11)),
                ('airline', models.CharField(max_length=32)),
                ('ke', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('use', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
