# Generated by Django 5.0.1 on 2024-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_flight_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=11)),
                ('yearQ1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('yearQuarter', models.CharField(max_length=11)),
                ('before_congestion', models.DecimalField(decimal_places=3, max_digits=5)),
                ('svm_linear', models.DecimalField(decimal_places=2, max_digits=5)),
                ('svm_ploy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('svm_rbf', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lstm', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lstm_pred', models.DecimalField(decimal_places=3, max_digits=5)),
                ('yearQ3_city', models.CharField(max_length=11)),
                ('Q3congestion', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Q3congestion_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Q3congestion_delay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yearQ3_weekend_city', models.CharField(max_length=11)),
                ('Q3congestion_weekend', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Q3congestion_weekend_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.CharField(max_length=11)),
                ('congestion', models.DecimalField(decimal_places=3, max_digits=5)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('congestion_weekend', models.DecimalField(decimal_places=3, max_digits=5)),
                ('speed_weekend', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('out', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
