# Generated by Django 5.0.1 on 2024-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_traffic_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_data',
            name='Q3congestion',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='Q3congestion_delay',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='Q3congestion_speed',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='Q3congestion_weekend',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='Q3congestion_weekend_speed',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='before_congestion',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='city',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='congestion',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='congestion_weekend',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='lstm',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='lstm_pred',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='out',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='speed',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='speed_weekend',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='svm_linear',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='svm_ploy',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='svm_rbf',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='time',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='year',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='yearQ1',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='yearQ3_city',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='yearQ3_weekend_city',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='traffic_data',
            name='yearQuarter',
            field=models.CharField(default='', max_length=11),
        ),
    ]
