# Generated by Django 5.0.1 on 2024-02-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_alter_traffic_data_q3congestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', max_length=90, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='say',
            field=models.CharField(default='', max_length=16),
        ),
    ]
