# Generated by Django 5.0.1 on 2024-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_user_email_user_image_user_say'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='say',
            field=models.CharField(default='', max_length=100),
        ),
    ]
